# Benchmarking configuration

# Number of benchmarks to be run for each stack
benchmarks: 3

# Concurency for Apache Benchmarking Tool
concurency: 100

# Number of requests to perform for the benchmarking session
requests: 100000

# Number of seconds to wait between benchmarks
sleep: 5

# Results data file
results: 'results/data.json'
