version: '3.2'

services:
  app:
    volumes:
      - ../../apps/php/:/var/www/magento1
      - ./etc/nginx/sites-available/magento1.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mariadb:10.1
    container_name: benchmarks-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
    networks:
      - benchmarks
