version: '3.2'

services:
  app:
    volumes:
      - ../../../apps/magento2:/var/www/html
      - ./etc/nginx/sites-available/magento2.conf:/etc/nginx/sites-available/default
  db:
    image: mariadb:10.1
    container_name: benchmarks-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
    networks:
      - benchmarks
