version: '3.2'

services:
  app:
    environment:
      - APP=php-swoole
    ports:
      - 8088:8088
    volumes:
      - ../../apps/swoole/:/var/www/app
      - ./etc/nginx/sites-available/swoole.conf:/etc/nginx/conf.d/default.conf
