version: '3.2'

services:
  app:
    environment:
      - APP=symfony-swoole
    ports:
      - 8086:8086
    volumes:
      - ../../apps/symfony/:/var/www/app
      - ./etc/nginx/sites-available/symfony-swoole.conf:/etc/nginx/conf.d/default.conf
