version: '3.2'

services:
  app:
    ports:
      - 8085:8085
    volumes:
      - ../../apps/symfony/:/var/www/app
      - ./etc/nginx/sites-available/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./usr/local/etc/php-fpm.d/www.conf-tcp:/usr/local/etc/php-fpm.d/www.conf
