version: '3.1'

services:
  app:
    container_name: benchmarks-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ../../apps/php-app:/var/www/html
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
