version: '3.1'

services:
  app:
    container_name: benchmarks-app
    image: petk/benchmarks:php-pm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ../../apps/symfony/:/var/www/symfony
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
