version: '3.0'

services:
  benchmarks-nginx-php-uds:
    container_name: benchmarks-nginx-php-uds
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    volumes:
      - ../../apps/php-app/:/var/www/html
      - ../../apps/laravel/:/var/www/laravel
      - ../../apps/symfony/:/var/www/symfony
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
