version: '2.1'

services:
  benchmarks-nginx-swoole-uds:
    container_name: benchmarks-nginx-swoole-uds
    build:
      context: ../../
      dockerfile: ./servers/nginx-swoole-uds/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../../apps/swoole-app/:/var/www/html
