version: '3.0'

services:
  benchmarks-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ../../apps/static:/usr/share/nginx/html
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
