version: '3.1'

services:
  app:
    container_name: benchmarks-app
    image: petk/benchmarks:nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
