version: '3.1'

services:
  app:
    container_name: benchmarks-app
    image: petk/benchmarks:nginx-fpm-uds
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ../../apps/php-app/:/var/www/html
      - ../../apps/laravel/:/var/www/laravel
      - ../../apps/symfony/:/var/www/symfony
      - ../../apps/magento1/:/var/www/magento1
    networks:
      - benchmarks

networks:
  benchmarks:
    driver: bridge
